### ISSUE TITLE
Quickly switching stocks results in an early dismiss

### ISSUE THREAD

**Issue by AvdLee** [AvdLee/StockAnalyzerApp#22]
When the stock sheet is dismissed and another stick is immediately selected, the newly opened stock sheet dismisses automatically.

> Select NVDA > swipe down to dismiss sheet > immediately select AAPL > sheet dismissed automatically

**Comment by peteratdiscovermotion** [comment]
https://user-images.githubusercontent.com/50426241/159734408-e0c045f1-52fb-487d-9422-17da37fea18a.mov

**Comment by AvdLee** [comment]
Reproduced and fixed in an upcoming build!

**Comment by peteratdiscovermotion** [comment]
Nice! Do you mind sharing the issue and fix?
