### ISSUE TITLE
Add ETF support

### ISSUE THREAD

**Issue by AvdLee** [AvdLee/StockAnalyzerApp#85]
### Discussed in https://github.com/AvdLee/StockAnalyzerApp/discussions/58

<div type='discussions-op-text'>

<sup>Originally posted by **AvdLee** April 25, 2022</sup>
Dedicated ETF support would be super valuable. Ideas:

- [x] Costs of ETF, how much do you pay for ETF maintenance?
- [x] ETF Spread. 90% Tesla is not a good ETF
- [x] Number of holdings, the more the better?
- [x] ETF coverage: which continents are included?</div>

**Comment by AvdLee** [comment]
Implemented in 3.0.0

**Comment by StuMinch** [comment]
Woohoo!
