### ISSUE TITLE
How to add multiple watchlists and stock purchases 

### ISSUE THREAD

**Issue by gbrooker** [AvdLee/StockAnalyzerApp#91]
Only one watchlist ? How can I add a pharma watchlist a tech watchlist etc ?

how can I track purchases of stocks and the value of my holding ?

**Comment by AvdLee** [comment]
> Only one watchlist ? How can I add a pharma watchlist a tech watchlist etc ?

This is a feature request and tracked here: 
https://github.com/AvdLee/StockAnalyzerApp/discussions/37

> how can I track purchases of stocks and the value of my holding ?
This is not going to be part of the app. Stock Analyzer solely focuses on analyzing, not tracking holdings.
